Nymph Game Engine: Events::Observer Class Reference
Events::Observer Class Reference abstract
Interface to be notified of an item's changes.
#include <observer.h>
Public Member Functions
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
virtual void onNotifyNow (std::shared_ptr< Event > event)=0
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Event > event)=0
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Protected Member Functions
std::shared_ptr< Event > getEvent ()
bool eventsWaiting () const noexcept
Detailed Description
Interface to be notified of an item's changes.
Constructor & Destructor Documentation
virtual Events::Observer::~Observer () inline virtual
Member Function Documentation
bool Events::Observer::eventsWaiting () const inline protected noexcept
Referenced by getEvent(), Graphics::TileAnimator< StateType >::onUpdate(), Game::SpriteMovement::onUpdate(), and processEventQueue().
std::shared_ptr<Event> Events::Observer::getEvent () inline protected
References eventsWaiting().
Referenced by Graphics::TileAnimator< StateType >::onUpdate(), Game::SpriteMovement::onUpdate(), and processEventQueue().
virtual void Events::Observer::handleQueuedEvent (std::shared_ptr< Event > event) pure virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::Camera, Graphics::UI::Element, Component, Script::ScriptObject, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextArea, Graphics::UI::TextField, Input::InputSystem, Graphics::UI::Area, Graphics::UI::Button, Sound::SoundInstance, and Utility::DebugParser.
Referenced by processEventQueue().
void Events::Observer::onNotify (std::shared_ptr< Event > event) inline
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
Parameters
[in] event The event
virtual void Events::Observer::onNotifyNow (std::shared_ptr< Event > event) pure virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::Camera, Graphics::UI::Element, Component, Script::ScriptObject, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, Input::InputSystem, Graphics::UI::Button, Sound::SoundInstance, and Utility::DebugParser.
void Events::Observer::processEventQueue () inline
This should be called once ever loop for every Observer to properly use queued events.
References eventsWaiting(), getEvent(), and handleQueuedEvent().
Referenced by Utility::DebugParser::handleEvents(), and Script::ScriptObject::onUpdate().
The documentation for this class was generated from the following file:
src/events/observer.h