Nymph Game Engine: Game::SpriteMoveEvent Class Reference
Game::SpriteMoveEvent Class Reference
Class for sprite move event.
#include <sprite_move_event.h>
Public Member Functions
SpriteMoveEvent (const glm::vec2 &velocity, const glm::vec2 &next_position)
SpriteMoveEvent constructor.
glm::vec2 getVelocity () const noexcept
Gets the velocity.
glm::vec2 getNextPosition () const noexcept
Gets the next position.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr
< SpriteMoveEvent > create (glm::vec2 &velocity, const glm::vec2 &next_position)
SpriteMoveEvent factory function.
Detailed Description
Class for sprite move event.
Constructor & Destructor Documentation
Game::SpriteMoveEvent::SpriteMoveEvent (const glm::vec2 & velocity, const glm::vec2 & next_position) inline
SpriteMoveEvent constructor.
Parameters
[in] velocity The velocity
[in] next_position The next position
Member Function Documentation
static std::shared_ptr<SpriteMoveEvent> Game::SpriteMoveEvent::create (glm::vec2 & velocity, const glm::vec2 & next_position) inline static
SpriteMoveEvent factory function.
Parameters
velocity The velocity
[in] next_position The next position
Returns
A newly constructed SpriteMoveEvent
Referenced by Game::SpriteMovementMotor::MoveUpReactor::enterState(), Game::SpriteMovementMotor::MoveDownReactor::enterState(), Game::SpriteMovementMotor::MoveLeftReactor::enterState(), Game::SpriteMovementMotor::MoveRightReactor::enterState(), and generated::getSpriteMoveEventModule().
glm::vec2 Game::SpriteMoveEvent::getNextPosition () const inline noexcept
Gets the next position.
Returns
The next position.
Referenced by generated::getSpriteMoveEventModule().
glm::vec2 Game::SpriteMoveEvent::getVelocity () const inline noexcept
Gets the velocity.
Returns
The velocity.
Referenced by generated::getSpriteMoveEventModule().
The documentation for this class was generated from the following file:
src/game/sprite_move_event.h