Nymph Game Engine: Component Class Reference
Component Class Reference abstract
Base Class for all components.
#include <component.h>
Public Member Functions
Component ()
Component constructor.
virtual void onStart ()=0
Called when the engine starts and when a new scene is loaded.
virtual bool onUpdate (const double delta)=0
Called every engine loop.
virtual void onDestroy ()=0
Called when the engine is shutting down.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
bool isActive () const noexcept
Determines if active.
unsigned int getId () const noexcept
Gets the identifier.
virtual std::string to_string () const noexcept
Returns a string representation of the object.
virtual std::string className () const noexcept
Returns a string representing the class name.
virtual unsigned long long getValueForSorting () const =0
Gets the value for sorting.
bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
virtual void log (el::base::type::ostream_t &os) const override
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Protected Attributes
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes
static unsigned int next_id = 0
Friends
class ComponentManager
class Entity
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
bool eventsWaiting () const noexcept
Detailed Description
Base Class for all components.
Constructor & Destructor Documentation
Component::Component ()
Component constructor.
References next_id, and transform.
virtual Component::~Component () inline virtual
Destroys the object.
Member Function Documentation
std::string Component::className () const virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented in Game::SpriteMovement, Graphics::Renderable, Graphics::Light, Graphics::Camera, Graphics::UI::Element, Graphics::TileAnimator< StateType >, Graphics::UI::Text, Graphics::UI::TextArea, Graphics::UI::WrappableText, Graphics::UI::TextField, Graphics::UI::Button, Graphics::UI::Area, and Graphics::UI::QuitButton.
Referenced by generated::getComponentModule(), and to_string().
unsigned int Component::getId () const noexcept
Gets the identifier.
Returns
The identifier.
References id.
Referenced by generated::getComponentModule(), Graphics::Camera::getValueForSorting(), Graphics::Light::getValueForSorting(), Graphics::TileAnimator< StateType >::getValueForSorting(), Game::SpriteMovement::getValueForSorting(), and to_string().
std::shared_ptr< Transform > Component::getTransform () const noexcept
Gets the transform.
Returns
The transform.
References transform.
Referenced by Graphics::UI::Element::Element(), generated::getComponentModule(), Graphics::UI::Text::getValueForSorting(), Graphics::UI::Element::getValueForSorting(), Graphics::Renderable::getValueForSorting(), Graphics::Camera::handleQueuedEvent(), Graphics::Light::influenceOnComponent(), Graphics::Camera::isComponentWithin(), Graphics::Light::log(), Graphics::Camera::onStart(), Graphics::UI::TextField::onStart(), Game::SpriteMovement::onStart(), Graphics::Camera::onUpdate(), Graphics::UI::Text::onUpdate(), Graphics::Renderable::onUpdate(), Graphics::UI::Text::renderCharacter(), Engine::setup(), Game::SpriteMovement::SpriteMovement(), Graphics::UI::TextArea::TextArea(), and to_string().
virtual unsigned long long Component::getValueForSorting () const pure virtual
Gets the value for sorting.
Returns
The value for sorting.
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::Light, Graphics::Camera, Graphics::UI::Element, Graphics::UI::Text, Sound::SoundInstance, and Physics::CollisionData.
Referenced by to_string().
void Component::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Implements Events::Observer.
Reimplemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::Camera, Graphics::UI::Element, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, Graphics::UI::Button, and Sound::SoundInstance.
References entity, Events::SET_ACTIVE, Events::SET_ENTITY_ACTIVE, and setActive().
Referenced by Graphics::UI::Text::handleQueuedEvent(), Graphics::Camera::handleQueuedEvent(), Graphics::TileAnimator< StateType >::handleQueuedEvent(), Graphics::Renderable::handleQueuedEvent(), Game::SpriteMovement::handleQueuedEvent(), and onNotifyNow().
bool Component::isActive () const noexcept
Determines if active.
Returns
True if active, False otherwise.
References active.
Referenced by generated::getComponentModule(), Graphics::UI::Element::handleQueuedEvent(), Graphics::UI::TextField::onKeyDown(), Graphics::UI::WrappableText::onUpdate(), Graphics::UI::Text::onUpdate(), Graphics::Renderable::onUpdate(), and to_string().
void Component::log (el::base::type::ostream_t & os) const override virtual
Reimplemented in Game::SpriteMovement, Graphics::TileAnimator< StateType >, Graphics::Renderable, Graphics::UI::Element, Graphics::Camera, Graphics::Light, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, Graphics::UI::Button, and Physics::CollisionData.
References to_string().
Referenced by Graphics::Camera::log(), and Graphics::TileAnimator< StateType >::log().
virtual void Component::onDestroy () pure virtual
Called when the engine is shutting down.
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::UI::Element, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextField, Graphics::UI::TextArea, Graphics::Camera, Graphics::UI::Area, Graphics::Light, Sound::SoundInstance, and Physics::CollisionData.
void Component::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Implements Events::Observer.
Reimplemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::Camera, Graphics::UI::Element, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, Graphics::UI::Button, and Sound::SoundInstance.
References handleQueuedEvent().
virtual void Component::onStart () pure virtual
Called when the engine starts and when a new scene is loaded.
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::UI::Element, Graphics::TileAnimator< StateType >, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextField, Graphics::UI::TextArea, Graphics::Camera, Graphics::UI::Area, Graphics::Light, Sound::SoundInstance, and Physics::CollisionData.
virtual bool Component::onUpdate (const double delta) pure virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implemented in Game::SpriteMovement, Graphics::Renderable, Graphics::TileAnimator< StateType >, Graphics::UI::Element, Graphics::UI::Text, Graphics::UI::WrappableText, Graphics::UI::TextField, Graphics::UI::TextArea, Graphics::Camera, Graphics::UI::Area, Graphics::Light, Sound::SoundInstance, and Physics::CollisionData.
bool Component::operator< (Component & other) noexcept
Operator < using getValueForSorting.
Parameters
other The other
Returns
true if this shoule be sorted before other
void Component::setActive (const bool active) noexcept
Sets the component active or inactive.
Parameters
[in] active True if active
Referenced by generated::getComponentModule(), handleQueuedEvent(), and Graphics::UI::TextField::onKeyDown().
void Component::setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
Parameters
[in] transform The transform
References transform.
Referenced by generated::getComponentModule().
std::string Component::to_string () const virtual noexcept
Returns a string representation of the object.
Returns
String representation of the object.
Reimplemented in Game::SpriteMovement, Graphics::Renderable, Graphics::UI::Element, Graphics::UI::Text, Graphics::UI::TextArea, Graphics::UI::WrappableText, Graphics::UI::TextField, Graphics::UI::Area, and Physics::CollisionData.
References className(), getId(), getTransform(), getValueForSorting(), and isActive().
Referenced by generated::getComponentModule(), log(), Graphics::UI::Text::to_string(), Graphics::Renderable::to_string(), and Game::SpriteMovement::to_string().
Friends And Related Function Documentation
friend class ComponentManager friend
friend class Entity friend
Member Data Documentation
bool Component::active protected
Referenced by isActive(), Graphics::Camera::onUpdate(), Graphics::TileAnimator< StateType >::onUpdate(), and Game::SpriteMovement::onUpdate().
std::weak_ptr<Entity> Component::entity protected
Referenced by handleQueuedEvent().
unsigned int Component::id protected
Referenced by getId().
unsigned int Component::next_id = 0 static protected
Referenced by Component().
std::shared_ptr<Transform> Component::transform protected
Referenced by Component(), getTransform(), Graphics::UI::WrappableText::onUpdate(), and setTransform().
The documentation for this class was generated from the following files:
src/component.h
src/component.cpp