Nymph Game Engine: Game::Scene Class Reference
Game::Scene Class Reference
A container holding a base transform, a vector of components, and a vector of entities.
#include <scene.h>
Public Member Functions
Scene ()=delete
Scene (const std::string scene_name)
Scene constructor.
void setTransform (std::shared_ptr< Transform > transform) noexcept
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void addComponent (std::shared_ptr< Component > component)
Adds a component.
void addComponent (std::shared_ptr< Physics::CollisionData > collision_data)
Adds a collision data component.
void addComponents (std::vector< std::shared_ptr< Component >> components)
Adds components.
std::vector< std::shared_ptr
< Component > > getComponents () const noexcept
Gets all components.
std::shared_ptr
< Physics::CollisionData > getCollisionData () const noexcept
Gets the collision data.
void addEntity (std::shared_ptr< Entity > entity) noexcept
Adds an entity.
void addEntities (std::vector< std::shared_ptr< Entity >> entities) noexcept
Adds entities.
std::vector< std::shared_ptr
< Entity > > getEntities () const noexcept
Gets all entities.
void setName (const std::string name) noexcept
Sets the name.
std::string getName () const noexcept
Gets the name.
std::string to_string () const noexcept
Returns a string representation of the object, mostly for use in chaiscript.
Detailed Description
A container holding a base transform, a vector of components, and a vector of entities.
Constructor & Destructor Documentation
Game::Scene::Scene () delete
Game::Scene::Scene (const std::string scene_name)
Scene constructor.
Parameters
[in] scene_name The name of the scene.
Member Function Documentation
void Game::Scene::addComponent (std::shared_ptr< Component > component)
Adds a component.
Parameters
[in] component The component
Referenced by generated::getSceneModule().
void Game::Scene::addComponent (std::shared_ptr< Physics::CollisionData > collision_data)
Adds a collision data component.
Parameters
[in] collision_data The collision data
void Game::Scene::addComponents (std::vector< std::shared_ptr< Component >> components)
Adds components.
Parameters
[in] components The components
Referenced by generated::getSceneModule().
void Game::Scene::addEntities (std::vector< std::shared_ptr< Entity >> entities) noexcept
Adds entities.
Parameters
[in] entities The entities
Referenced by generated::getSceneModule().
void Game::Scene::addEntity (std::shared_ptr< Entity > entity) noexcept
Adds an entity.
Parameters
[in] entity The entity
Referenced by generated::getSceneModule().
std::shared_ptr< Physics::CollisionData > Game::Scene::getCollisionData () const noexcept
Gets the collision data.
Returns
The collision data.
Referenced by generated::getSceneModule(), and to_string().
std::vector< std::shared_ptr< Component > > Game::Scene::getComponents () const noexcept
Gets all components.
Returns
A vector of components
Referenced by generated::getSceneModule().
std::vector< std::shared_ptr< Entity > > Game::Scene::getEntities () const noexcept
Gets all entities.
Returns
A vector of entities
Referenced by generated::getSceneModule().
std::string Game::Scene::getName () const noexcept
Gets the name.
Returns
The name.
Referenced by generated::getSceneModule(), and to_string().
std::shared_ptr< Transform > Game::Scene::getTransform () const noexcept
Gets the transform.
Returns
The transform.
Referenced by generated::getSceneModule().
void Game::Scene::setName (const std::string name) noexcept
Sets the name.
Parameters
[in] name The name
Referenced by generated::getSceneModule().
void Game::Scene::setTransform (std::shared_ptr< Transform > transform) noexcept
Sets the transform.
Parameters
[in] transform The transform
Referenced by generated::getSceneModule().
std::string Game::Scene::to_string () const noexcept
Returns a string representation of the object, mostly for use in chaiscript.
Returns
String representation of the object.
References getCollisionData(), and getName().
Referenced by generated::getSceneModule().
The documentation for this class was generated from the following files:
src/game/scene.h
src/game/scene.cpp