Nymph Game Engine: Graphics::TileAnimator< StateType > Class Template Reference
Graphics::TileAnimator< StateType > Class Template Reference
Class for tile animator.
#include <tile_animator.hpp>
Public Member Functions
TileAnimator ()=delete
TileAnimator (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width_pixels, const unsigned int tile_height_pixels)
TileAnimator Constructor.
void setStartingState (const StateType &state)
Sets the starting state.
void addFrameFront (const StateType &state, const glm::ivec2 &frame_pos, const unsigned int frame_time, bool set_current=false)
Adds a frame to the front.
void addFrameBack (const StateType &state, const glm::ivec2 &frame_pos, const unsigned int frame_time, bool set_current=false)
Adds a frame to the back.
void popFrameFront (const StateType &state)
Pops a frame from the front.
void popFrameBack (const StateType &state)
Pops a frame from the back.
void triggerAnimation (const StateType &state)
Triggers animation of state.
virtual std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual bool onUpdate (const double delta) override
Called every engine loop.
virtual void onDestroy () override
Called when the engine is shutting down.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
bool isActive () const noexcept
Determines if active.
unsigned int getId () const noexcept
Gets the identifier.
virtual std::string to_string () const noexcept
Returns a string representation of the object.
bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Public Member Functions inherited from Cloneable< TileAnimator< StateType > >
virtual ~Cloneable ()
std::shared_ptr< TileAnimator
< StateType > > clone ()
Static Public Member Functions
static std::shared_ptr
< TileAnimator< StateType > > create (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width, const unsigned int tile_height)
Factory function for TileAnimator.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
bool eventsWaiting () const noexcept
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
template<typename StateType>
class Graphics::TileAnimator< StateType >
Class for tile animator.
Constructor & Destructor Documentation
template<typename StateType> Graphics::TileAnimator< StateType >::TileAnimator () delete
template<typename StateType> Graphics::TileAnimator< StateType >::TileAnimator (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width_pixels, const unsigned int tile_height_pixels) inline
TileAnimator Constructor.
Parameters
[in] tileset_width The tileset width
[in] tileset_height The tileset height
[in] tile_width_pixels The tile width pixels
[in] tile_height_pixels The tile height pixels
Member Function Documentation
template<typename StateType> void Graphics::TileAnimator< StateType >::addFrameBack (const StateType & state, const glm::ivec2 & frame_pos, const unsigned int frame_time, bool set_current = false) inline
Adds a frame to the back.
Parameters
[in] state The state
[in] frame_pos The frame position
[in] frame_time The frame time
[in] set_current The set current
template<typename StateType> void Graphics::TileAnimator< StateType >::addFrameFront (const StateType & state, const glm::ivec2 & frame_pos, const unsigned int frame_time, bool set_current = false) inline
Adds a frame to the front.
Parameters
[in] state The state
[in] frame_pos The frame position
[in] frame_time The frame time
[in] set_current The set current
template<typename StateType> virtual std::string Graphics::TileAnimator< StateType >::className () const inline override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
template<typename StateType> static std::shared_ptr<TileAnimator<StateType> > Graphics::TileAnimator< StateType >::create (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width, const unsigned int tile_height) inline static
Factory function for TileAnimator.
Parameters
[in] tileset_width The tileset width
[in] tileset_height The tileset height
[in] tile_width The tile width
[in] tile_height The tile height
Returns
Newly created TileAnimator
template<typename StateType> virtual unsigned long long Graphics::TileAnimator< StateType >::getValueForSorting () const inline override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
References Component::getId().
template<typename StateType> void Graphics::TileAnimator< StateType >::handleQueuedEvent (std::shared_ptr< Events::Event > event) inline override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
References Events::ANIMATION_TRIGGER, Component::handleQueuedEvent(), and Graphics::TileAnimator< StateType >::triggerAnimation().
Referenced by Graphics::TileAnimator< StateType >::onNotifyNow(), and Graphics::TileAnimator< StateType >::onUpdate().
template<typename StateType> virtual void Graphics::TileAnimator< StateType >::log (el::base::type::ostream_t & os) const inline virtual
Reimplemented from Component.
References Component::log().
template<typename StateType> virtual void Graphics::TileAnimator< StateType >::onDestroy () inline override virtual
Called when the engine is shutting down.
Implements Component.
template<typename StateType> void Graphics::TileAnimator< StateType >::onNotifyNow (std::shared_ptr< Events::Event > event) inline override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
References Graphics::TileAnimator< StateType >::handleQueuedEvent().
template<typename StateType> virtual void Graphics::TileAnimator< StateType >::onStart () inline override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
References Graphics::SetUniformEvent::create(), Events::Subject::notify(), and Graphics::Uniform::setData().
template<typename StateType> virtual bool Graphics::TileAnimator< StateType >::onUpdate (const double delta) inline override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
References Component::active, Graphics::SetUniformEvent::create(), Events::Observer::eventsWaiting(), Events::Observer::getEvent(), Graphics::TileAnimator< StateType >::handleQueuedEvent(), Events::Subject::notifyNow(), and Graphics::Uniform::setData().
template<typename StateType> void Graphics::TileAnimator< StateType >::popFrameBack (const StateType & state) inline
Pops a frame from the back.
Parameters
[in] state The state
template<typename StateType> void Graphics::TileAnimator< StateType >::popFrameFront (const StateType & state) inline
Pops a frame from the front.
Parameters
[in] state The state
template<typename StateType> void Graphics::TileAnimator< StateType >::setStartingState (const StateType & state) inline
Sets the starting state.
Parameters
[in] state The state
template<typename StateType> void Graphics::TileAnimator< StateType >::triggerAnimation (const StateType & state) inline
Triggers animation of state.
Parameters
[in] state The state
Referenced by Graphics::TileAnimator< StateType >::handleQueuedEvent().
The documentation for this class was generated from the following file:
src/graphics/tile_animator.hpp