Nymph Game Engine: generated Namespace Reference
generated Namespace Reference
Functions
chaiscript::ModulePtr getEventTypeModule ()
chaiscript::ModulePtr getLightTypeModule ()
chaiscript::ModulePtr getWrappableTextHorizontalAlignmentModule ()
chaiscript::ModulePtr getWrappableTextVerticalAlignmentModule ()
chaiscript::ModulePtr getEntityModule ()
chaiscript::ModulePtr getComponentModule ()
chaiscript::ModulePtr getTransformModule ()
chaiscript::ModulePtr getSetEntityActiveEventModule ()
chaiscript::ModulePtr getComponentManagerModule ()
chaiscript::ModulePtr getSetActiveEventModule ()
chaiscript::ModulePtr getEngineModule ()
chaiscript::ModulePtr getInputSystemModule ()
chaiscript::ModulePtr getMouseScrollEventModule ()
chaiscript::ModulePtr getMouseButtonUpEventModule ()
chaiscript::ModulePtr getMouseCursorEventModule ()
chaiscript::ModulePtr getCharacterTypedEventModule ()
chaiscript::ModulePtr getKeyUpEventModule ()
chaiscript::ModulePtr getKeyDownEventModule ()
chaiscript::ModulePtr getKeyRepeatEventModule ()
chaiscript::ModulePtr getCursorEnterEventModule ()
chaiscript::ModulePtr getMouseButtonDownEventModule ()
chaiscript::ModulePtr getCursorLeaveEventModule ()
chaiscript::ModulePtr getSubjectModule ()
chaiscript::ModulePtr getEventModule ()
chaiscript::ModulePtr getListLayersEventModule ()
chaiscript::ModulePtr getLoadMapEventModule ()
chaiscript::ModulePtr getFPSCounterModule ()
chaiscript::ModulePtr getToggleLayerEventModule ()
chaiscript::ModulePtr getWindowExitEventModule ()
chaiscript::ModulePtr getListCharactersEventModule ()
chaiscript::ModulePtr getListMapsEventModule ()
chaiscript::ModulePtr getConfigManagerModule ()
chaiscript::ModulePtr getLoadCharacterEventModule ()
chaiscript::ModulePtr getDebugParserModule ()
chaiscript::ModulePtr getToggleLightsEventModule ()
chaiscript::ModulePtr getToggleFreeCameraEventModule ()
chaiscript::ModulePtr getScriptObjectModule ()
chaiscript::ModulePtr getSceneModule ()
chaiscript::ModulePtr getSceneGeneratorModule ()
chaiscript::ModulePtr getSpriteMovementModule ()
chaiscript::ModulePtr getMapModule ()
chaiscript::ModulePtr getSpriteMoveEventModule ()
chaiscript::ModulePtr getGraphicsSystemModule ()
chaiscript::ModulePtr getTextureManagerModule ()
chaiscript::ModulePtr getSetUniformEventModule ()
chaiscript::ModulePtr getRenderableModule ()
chaiscript::ModulePtr getCameraModule ()
chaiscript::ModulePtr getLightModule ()
chaiscript::ModulePtr getShaderModule ()
chaiscript::ModulePtr getBaseTextureModule ()
chaiscript::ModulePtr getShaderManagerModule ()
chaiscript::ModulePtr getAreaModule ()
chaiscript::ModulePtr getChangeTextEventModule ()
chaiscript::ModulePtr getTextAreaModule ()
chaiscript::ModulePtr getTextFieldModule ()
chaiscript::ModulePtr getWrappableTextModule ()
chaiscript::ModulePtr getSkinModule ()
chaiscript::ModulePtr getElementModule ()
chaiscript::ModulePtr getSuspendKeyInputEventModule ()
chaiscript::ModulePtr getFontModule ()
chaiscript::ModulePtr getFontGeneratorModule ()
chaiscript::ModulePtr getQuitButtonModule ()
chaiscript::ModulePtr getResumeKeyInputEventModule ()
chaiscript::ModulePtr getTextModule ()
chaiscript::ModulePtr getButtonModule ()
void registerModules (std::shared_ptr< chaiscript::ChaiScript > chai)
Function Documentation
chaiscript::ModulePtr generated::getAreaModule ()
References Graphics::UI::Area::className(), Graphics::UI::Area::create(), Graphics::UI::Area::onCursorEnter(), Graphics::UI::Area::onCursorLeave(), Graphics::UI::Area::onKeyDown(), Graphics::UI::Area::onKeyRepeat(), Graphics::UI::Area::onKeyUp(), Graphics::UI::Area::onLeftClick(), Graphics::UI::Area::onLeftClickRelease(), Graphics::UI::Area::onRightClick(), Graphics::UI::Area::onRightClickRelease(), Graphics::UI::Area::onScroll(), and Graphics::UI::Area::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getBaseTextureModule ()
References Graphics::BaseTexture::bind(), Graphics::BaseTexture::getHeight(), Graphics::BaseTexture::getName(), Graphics::BaseTexture::getWidth(), Graphics::BaseTexture::isLoaded(), Graphics::BaseTexture::load(), Graphics::BaseTexture::setName(), and Graphics::BaseTexture::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getButtonModule ()
References Graphics::UI::Button::className(), Graphics::UI::Button::create(), Graphics::UI::Button::onCursorEnter(), Graphics::UI::Button::onCursorLeave(), Graphics::UI::Button::onKeyDown(), Graphics::UI::Button::onKeyRepeat(), Graphics::UI::Button::onKeyUp(), Graphics::UI::Button::onLeftClick(), Graphics::UI::Button::onLeftClickRelease(), Graphics::UI::Button::onRightClick(), Graphics::UI::Button::onRightClickRelease(), and Graphics::UI::Button::onScroll().
Referenced by registerModules().
chaiscript::ModulePtr generated::getCameraModule ()
References Graphics::Camera::className(), Graphics::Camera::getFar(), Graphics::Camera::getFreeCameraSpeed(), Graphics::Camera::getHeight(), Graphics::Camera::getNear(), Graphics::Camera::getProjectionMatrix(), Graphics::Camera::getScreenPaddingInTiles(), Graphics::Camera::getWidth(), Graphics::Camera::isComponentWithin(), Graphics::Camera::setFar(), Graphics::Camera::setFreeCameraSpeed(), Graphics::Camera::setHeight(), Graphics::Camera::setNear(), Graphics::Camera::setScreenPaddingInTiles(), and Graphics::Camera::setWidth().
Referenced by registerModules().
chaiscript::ModulePtr generated::getChangeTextEventModule ()
References Graphics::UI::ChangeTextEvent::create(), and Graphics::UI::ChangeTextEvent::getText().
Referenced by registerModules().
chaiscript::ModulePtr generated::getCharacterTypedEventModule ()
References Input::CharacterTypedEvent::create(), and Input::CharacterTypedEvent::getCharacter().
Referenced by registerModules().
chaiscript::ModulePtr generated::getComponentManagerModule ()
References ComponentManager::addComponent(), ComponentManager::addComponents(), ComponentManager::count(), ComponentManager::removeComponent(), and ComponentManager::removeComponents().
Referenced by registerModules().
chaiscript::ModulePtr generated::getComponentModule ()
References Component::className(), Component::getId(), Component::getTransform(), Component::isActive(), Component::setActive(), Component::setTransform(), and Component::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getConfigManagerModule ()
References Utility::ConfigManager::getBool(), Utility::ConfigManager::getDouble(), Utility::ConfigManager::getFloat(), Utility::ConfigManager::getInt(), Utility::ConfigManager::getString(), Utility::ConfigManager::getStringVector(), Utility::ConfigManager::getUnsignedInt(), and Utility::ConfigManager::getUnsignedIntVector().
Referenced by registerModules().
chaiscript::ModulePtr generated::getCursorEnterEventModule ()
References Input::CursorEnterEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getCursorLeaveEventModule ()
References Input::CursorLeaveEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getDebugParserModule ()
References Utility::DebugParser::handleEvents(), and Utility::DebugParser::parseCommand().
Referenced by registerModules().
chaiscript::ModulePtr generated::getElementModule ()
References Graphics::UI::Element::className(), Graphics::UI::Element::getAnchorPoint(), Graphics::UI::Element::getColor(), Graphics::UI::Element::getHeight(), Graphics::UI::Element::getSkin(), Graphics::UI::Element::getTextPadding(), Graphics::UI::Element::getWidth(), Graphics::UI::Element::isPointWithin(), Graphics::UI::Element::setAnchorPoint(), Graphics::UI::Element::setColor(), Graphics::UI::Element::setHeight(), Graphics::UI::Element::setSkin(), Graphics::UI::Element::setTextPadding(), Graphics::UI::Element::setWidth(), and Graphics::UI::Element::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getEngineModule ()
References Engine::activateScene(), Engine::addScene(), Engine::deactivateScene(), Engine::findSceneByName(), Engine::getActiveSceneNames(), Engine::getSceneNames(), Engine::getScenes(), and Engine::timeToExit().
Referenced by registerModules().
chaiscript::ModulePtr generated::getEntityModule ()
References Entity::addComponent(), Entity::getComponents(), Entity::getTransform(), Entity::isActive(), Entity::removeComponent(), and Entity::setActive().
Referenced by registerModules().
chaiscript::ModulePtr generated::getEventModule ()
References Events::Event::getEventType().
Referenced by registerModules().
chaiscript::ModulePtr generated::getEventTypeModule ()
References Events::ADD_TEXTURE, Events::ANIMATION_TRIGGER, Events::CHANGE_TEXT, Events::CHARACTER_TYPED, Events::CURSOR_ENTER, Events::CURSOR_LEAVE, Events::DEBUG_COMMAND, Events::KEY_DOWN, Events::KEY_REPEAT, Events::KEY_UP, Events::LIST_CHARACTERS, Events::LIST_LAYERS, Events::LIST_MAPS, Events::LOAD_CHARACTER, Events::LOAD_MAP, Events::MOUSE_BUTTON_DOWN, Events::MOUSE_BUTTON_UP, Events::MOUSE_CURSOR, Events::MOUSE_SCROLL, Events::REMOVE_TEXTURE, Events::RESUME_KEY_INPUT, Events::SET_ACTIVE, Events::SET_ENTITY_ACTIVE, Events::SET_SHADER, Events::SET_UNIFORM, Events::SPRITE_MOVE, Events::SUSPEND_KEY_INPUT, Events::TOGGLE_FREE_CAMERA, Events::TOGGLE_LAYER, Events::TOGGLE_LIGHTS, and Events::WINDOW_EXIT.
Referenced by registerModules().
chaiscript::ModulePtr generated::getFontGeneratorModule ()
References Graphics::UI::FontGenerator::getFont(), Graphics::UI::FontGenerator::getFontPath(), Graphics::UI::FontGenerator::loadFont(), and Graphics::UI::FontGenerator::setFontPath().
Referenced by registerModules().
chaiscript::ModulePtr generated::getFontModule ()
References Graphics::UI::Font::addCharacter(), Graphics::UI::Font::getCharacter(), Graphics::UI::Font::getCharacters(), Graphics::UI::Font::getOpenGLSize(), and Graphics::UI::Font::getSize().
Referenced by registerModules().
chaiscript::ModulePtr generated::getFPSCounterModule ()
References Utility::FPSCounter::getAverageFPS(), Utility::FPSCounter::getCurrentFPS(), Utility::FPSCounter::getMaxFPS(), and Utility::FPSCounter::resetAverageFPS().
Referenced by registerModules().
chaiscript::ModulePtr generated::getGraphicsSystemModule ()
References Graphics::GraphicsSystem::addLight(), Graphics::GraphicsSystem::addRenderable(), Graphics::GraphicsSystem::getMaxInfluenceLights(), Graphics::GraphicsSystem::removeLight(), Graphics::GraphicsSystem::removeRenderable(), Graphics::GraphicsSystem::renderablesCount(), Graphics::GraphicsSystem::setMaxInfluenceLights(), Graphics::GraphicsSystem::setWindowName(), Graphics::GraphicsSystem::windowHeight(), Graphics::GraphicsSystem::windowName(), and Graphics::GraphicsSystem::windowWidth().
Referenced by registerModules().
chaiscript::ModulePtr generated::getInputSystemModule ()
References Input::InputSystem::dummy().
Referenced by registerModules().
chaiscript::ModulePtr generated::getKeyDownEventModule ()
References Input::KeyDownEvent::create(), and Input::KeyDownEvent::getKey().
Referenced by registerModules().
chaiscript::ModulePtr generated::getKeyRepeatEventModule ()
References Input::KeyRepeatEvent::create(), and Input::KeyRepeatEvent::getKey().
Referenced by registerModules().
chaiscript::ModulePtr generated::getKeyUpEventModule ()
References Input::KeyUpEvent::create(), and Input::KeyUpEvent::getKey().
Referenced by registerModules().
chaiscript::ModulePtr generated::getLightModule ()
References Graphics::Light::castsQuantizedBands(), Graphics::Light::className(), Graphics::Light::getColor(), Graphics::Light::getConeAngle(), Graphics::Light::getConeDirection(), Graphics::Light::getIntensity(), Graphics::Light::getLinearAttenuation(), Graphics::Light::getNumberOfQuantizedBands(), Graphics::Light::getQuadraticAttenuation(), Graphics::Light::getType(), Graphics::Light::influenceOnComponent(), Graphics::Light::setColor(), Graphics::Light::setConeAngle(), Graphics::Light::setConeDirection(), Graphics::Light::setIntensity(), Graphics::Light::setLinearAttenuation(), Graphics::Light::setNumberOfQuantizedBands(), and Graphics::Light::setQuadraticAttenuation().
Referenced by registerModules().
chaiscript::ModulePtr generated::getLightTypeModule ()
References Graphics::Light::POINT, and Graphics::Light::SPOT.
Referenced by registerModules().
chaiscript::ModulePtr generated::getListCharactersEventModule ()
References Utility::ListCharactersEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getListLayersEventModule ()
References Utility::ListLayersEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getListMapsEventModule ()
References Utility::ListMapsEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getLoadCharacterEventModule ()
References Utility::LoadCharacterEvent::create(), and Utility::LoadCharacterEvent::getName().
Referenced by registerModules().
chaiscript::ModulePtr generated::getLoadMapEventModule ()
References Utility::LoadMapEvent::create(), and Utility::LoadMapEvent::getName().
Referenced by registerModules().
chaiscript::ModulePtr generated::getMapModule ()
References Game::Map::getPath().
Referenced by registerModules().
chaiscript::ModulePtr generated::getMouseButtonDownEventModule ()
References Input::MouseButtonDownEvent::create(), and Input::MouseButtonDownEvent::getButton().
Referenced by registerModules().
chaiscript::ModulePtr generated::getMouseButtonUpEventModule ()
References Input::MouseButtonUpEvent::create(), and Input::MouseButtonUpEvent::getButton().
Referenced by registerModules().
chaiscript::ModulePtr generated::getMouseCursorEventModule ()
References Input::MouseCursorEvent::create(), and Input::MouseCursorEvent::getPosition().
Referenced by registerModules().
chaiscript::ModulePtr generated::getMouseScrollEventModule ()
References Input::MouseScrollEvent::create(), and Input::MouseScrollEvent::getPosition().
Referenced by registerModules().
chaiscript::ModulePtr generated::getQuitButtonModule ()
References Graphics::UI::QuitButton::className(), Graphics::UI::QuitButton::create(), and Graphics::UI::QuitButton::onLeftClick().
Referenced by registerModules().
chaiscript::ModulePtr generated::getRenderableModule ()
References Graphics::Renderable::addInfluencingLight(), Graphics::Renderable::addTexture(), Graphics::Renderable::className(), Graphics::Renderable::clearInfluencingLights(), Graphics::Renderable::getAmbientIntensity(), Graphics::Renderable::getAmbientLight(), Graphics::Renderable::getShader(), Graphics::Renderable::getTextures(), Graphics::Renderable::isLightReactive(), Graphics::Renderable::removeTexture(), Graphics::Renderable::setAmbientIntensity(), Graphics::Renderable::setAmbientLight(), Graphics::Renderable::setLightReactive(), Graphics::Renderable::setShader(), and Graphics::Renderable::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getResumeKeyInputEventModule ()
References Graphics::UI::ResumeKeyInputEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSceneGeneratorModule ()
References Game::SceneGenerator::createSceneFromMap(), Game::SceneGenerator::getDynamicEntityByName(), Game::SceneGenerator::getDynamicEntityNames(), and Game::SceneGenerator::getStrippedMapName().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSceneModule ()
References Game::Scene::addComponent(), Game::Scene::addComponents(), Game::Scene::addEntities(), Game::Scene::addEntity(), Game::Scene::getCollisionData(), Game::Scene::getComponents(), Game::Scene::getEntities(), Game::Scene::getName(), Game::Scene::getTransform(), Game::Scene::setName(), Game::Scene::setTransform(), and Game::Scene::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getScriptObjectModule ()
References Script::ScriptObject::getClassName(), and Script::ScriptObject::setClassName().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSetActiveEventModule ()
References SetActiveEvent::create(), and SetActiveEvent::getActive().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSetEntityActiveEventModule ()
References SetEntityActiveEvent::create(), and SetEntityActiveEvent::getActive().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSetUniformEventModule ()
References Graphics::SetUniformEvent::create(), and Graphics::SetUniformEvent::getUniform().
Referenced by registerModules().
chaiscript::ModulePtr generated::getShaderManagerModule ()
References Graphics::ShaderManager::getShader(), Graphics::ShaderManager::loadShader(), and Graphics::ShaderManager::setUniformForAllPrograms().
Referenced by registerModules().
chaiscript::ModulePtr generated::getShaderModule ()
References Graphics::Shader::getName(), Graphics::Shader::getUniformNames(), Graphics::Shader::setName(), Graphics::Shader::setUniform(), and Graphics::Shader::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSkinModule ()
References Graphics::UI::Skin::getShader(), Graphics::UI::Skin::getTexture(), Graphics::UI::Skin::setShader(), and Graphics::UI::Skin::setTexture().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSpriteMoveEventModule ()
References Game::SpriteMoveEvent::create(), Game::SpriteMoveEvent::getNextPosition(), and Game::SpriteMoveEvent::getVelocity().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSpriteMovementModule ()
References Game::SpriteMovement::addCollisionData(), Game::SpriteMovement::className(), Game::SpriteMovement::setMoveQuantization(), Game::SpriteMovement::setMovingSpeed(), and Game::SpriteMovement::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSubjectModule ()
References Events::Subject::addObserver(), Events::Subject::notify(), Events::Subject::notifyNow(), and Events::Subject::removeObserver().
Referenced by registerModules().
chaiscript::ModulePtr generated::getSuspendKeyInputEventModule ()
References Graphics::UI::SuspendKeyInputEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getTextAreaModule ()
References Graphics::UI::TextArea::className(), Graphics::UI::TextArea::create(), Graphics::UI::TextArea::getText(), Graphics::UI::TextArea::onCursorEnter(), Graphics::UI::TextArea::onCursorLeave(), Graphics::UI::TextArea::onDestroy(), Graphics::UI::TextArea::onKeyDown(), Graphics::UI::TextArea::onKeyRepeat(), Graphics::UI::TextArea::onKeyUp(), Graphics::UI::TextArea::onLeftClick(), Graphics::UI::TextArea::onLeftClickRelease(), Graphics::UI::TextArea::onRightClick(), Graphics::UI::TextArea::onRightClickRelease(), Graphics::UI::TextArea::onScroll(), Graphics::UI::TextArea::onStart(), Graphics::UI::TextArea::onUpdate(), Graphics::UI::TextArea::setText(), and Graphics::UI::TextArea::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getTextFieldModule ()
References Graphics::UI::TextField::className(), Graphics::UI::TextField::create(), Graphics::UI::TextField::onCharacterTyped(), Graphics::UI::TextField::onCursorEnter(), Graphics::UI::TextField::onCursorLeave(), Graphics::UI::TextField::onKeyDown(), Graphics::UI::TextField::onKeyRepeat(), Graphics::UI::TextField::onKeyUp(), Graphics::UI::TextField::onLeftClick(), Graphics::UI::TextField::onLeftClickRelease(), Graphics::UI::TextField::onRightClick(), Graphics::UI::TextField::onRightClickRelease(), Graphics::UI::TextField::onScroll(), and Graphics::UI::TextField::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getTextModule ()
References Graphics::UI::Text::className(), Graphics::UI::Text::getColor(), Graphics::UI::Text::getKerning(), Graphics::UI::Text::getText(), Graphics::UI::Text::setColor(), Graphics::UI::Text::setFont(), Graphics::UI::Text::setKerning(), Graphics::UI::Text::setShader(), Graphics::UI::Text::setText(), and Graphics::UI::Text::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getTextureManagerModule ()
References Graphics::TextureManager::getTexture(), Graphics::TextureManager::loadTexture(), and Graphics::TextureManager::textureExists().
Referenced by registerModules().
chaiscript::ModulePtr generated::getToggleFreeCameraEventModule ()
References Utility::ToggleFreeCameraEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getToggleLayerEventModule ()
References Utility::ToggleLayerEvent::create(), Utility::ToggleLayerEvent::getLayerNumber(), and Utility::ToggleLayerEvent::turnOn().
Referenced by registerModules().
chaiscript::ModulePtr generated::getToggleLightsEventModule ()
References Utility::ToggleLightsEvent::create(), and Utility::ToggleLightsEvent::turnOn().
Referenced by registerModules().
chaiscript::ModulePtr generated::getTransformModule ()
References Transform::addChild(), Transform::getAbsoluteEulerAngles(), Transform::getAbsoluteRotation(), Transform::getAbsoluteRotationAngle(), Transform::getAbsoluteRotationAxis(), Transform::getAbsoluteScale(), Transform::getAbsoluteTransformationMatrix(), Transform::getAbsoluteTranslation(), Transform::getChildren(), Transform::getLocalEulerAngles(), Transform::getLocalRotation(), Transform::getLocalRotationAngle(), Transform::getLocalRotationAxis(), Transform::getLocalScale(), Transform::getLocalTransformationMatrix(), Transform::getLocalTranslation(), Transform::getParent(), Transform::getTreeSize(), Transform::removeChild(), Transform::rotate(), Transform::scale(), Transform::to_string(), and Transform::translate().
Referenced by registerModules().
chaiscript::ModulePtr generated::getWindowExitEventModule ()
References Utility::WindowExitEvent::create().
Referenced by registerModules().
chaiscript::ModulePtr generated::getWrappableTextHorizontalAlignmentModule ()
References Graphics::UI::WrappableText::HCENTER, Graphics::UI::WrappableText::LEFT, and Graphics::UI::WrappableText::RIGHT.
Referenced by registerModules().
chaiscript::ModulePtr generated::getWrappableTextModule ()
References Graphics::UI::WrappableText::className(), Graphics::UI::WrappableText::setHorizontalAlignment(), Graphics::UI::WrappableText::setLineSpacing(), Graphics::UI::WrappableText::setSize(), Graphics::UI::WrappableText::setText(), Graphics::UI::WrappableText::setVerticalAlignment(), and Graphics::UI::WrappableText::to_string().
Referenced by registerModules().
chaiscript::ModulePtr generated::getWrappableTextVerticalAlignmentModule ()
References Graphics::UI::WrappableText::BOTTOM, Graphics::UI::WrappableText::TOP, and Graphics::UI::WrappableText::VCENTER.
Referenced by registerModules().
void generated::registerModules (std::shared_ptr< chaiscript::ChaiScript > chai)
References getAreaModule(), getBaseTextureModule(), getButtonModule(), getCameraModule(), getChangeTextEventModule(), getCharacterTypedEventModule(), getComponentManagerModule(), getComponentModule(), getConfigManagerModule(), getCursorEnterEventModule(), getCursorLeaveEventModule(), getDebugParserModule(), getElementModule(), getEngineModule(), getEntityModule(), getEventModule(), getEventTypeModule(), getFontGeneratorModule(), getFontModule(), getFPSCounterModule(), getGraphicsSystemModule(), getInputSystemModule(), getKeyDownEventModule(), getKeyRepeatEventModule(), getKeyUpEventModule(), getLightModule(), getLightTypeModule(), getListCharactersEventModule(), getListLayersEventModule(), getListMapsEventModule(), getLoadCharacterEventModule(), getLoadMapEventModule(), getMapModule(), getMouseButtonDownEventModule(), getMouseButtonUpEventModule(), getMouseCursorEventModule(), getMouseScrollEventModule(), getQuitButtonModule(), getRenderableModule(), getResumeKeyInputEventModule(), getSceneGeneratorModule(), getSceneModule(), getScriptObjectModule(), getSetActiveEventModule(), getSetEntityActiveEventModule(), getSetUniformEventModule(), getShaderManagerModule(), getShaderModule(), getSkinModule(), getSpriteMoveEventModule(), getSpriteMovementModule(), getSubjectModule(), getSuspendKeyInputEventModule(), getTextAreaModule(), getTextFieldModule(), getTextModule(), getTextureManagerModule(), getToggleFreeCameraEventModule(), getToggleLayerEventModule(), getToggleLightsEventModule(), getTransformModule(), getWindowExitEventModule(), getWrappableTextHorizontalAlignmentModule(), getWrappableTextModule(), and getWrappableTextVerticalAlignmentModule().