Nymph Game Engine: Game::SpriteMovementMotor Struct Reference
Game::SpriteMovementMotor Struct Reference
#include <sprite_movement.h>
Classes
class FaceDownReactor
class FaceLeftReactor
class FaceRightReactor
class FaceUpReactor
class MoveDownReactor
class MoveLeftReactor
class MoveRightReactor
class MoveUpReactor
struct SpriteData
Sprite data to be exposed for FSM mutation.
Public Types
enum SpriteState : unsigned int {
MOVE_UP, FACE_UP, MOVE_DOWN, FACE_DOWN,
MOVE_LEFT, FACE_LEFT, MOVE_RIGHT, FACE_RIGHT
}
Sprite state enum.
enum SpriteInput : unsigned int {
LEFT, RIGHT, UP, DOWN,
NONE
}
Sprite input enum.
using SpriteFSM = Events::FSM::FSM< SpriteData, SpriteState, SpriteInput, MoveUpReactor, FaceUpReactor, MoveDownReactor, FaceDownReactor, MoveLeftReactor, FaceLeftReactor, MoveRightReactor, FaceRightReactor >
Static Public Member Functions
static std::shared_ptr
< SpriteData > defaultSpriteData ()
Create a default SpriteData POD.
static bool updateSprite (const std::shared_ptr< SpriteData > data, const SpriteState current_state, const double delta)
General sprite update for each reactor.
Member Typedef Documentation
using Game::SpriteMovementMotor::SpriteFSM = Events::FSM::FSM<SpriteData, SpriteState, SpriteInput, MoveUpReactor, FaceUpReactor, MoveDownReactor, FaceDownReactor, MoveLeftReactor, FaceLeftReactor, MoveRightReactor, FaceRightReactor>
Member Enumeration Documentation
enum Game::SpriteMovementMotor::SpriteInput : unsigned int
Sprite input enum.
Enumerator
LEFT
RIGHT
UP
DOWN
NONE
enum Game::SpriteMovementMotor::SpriteState : unsigned int
Sprite state enum.
Enumerator
MOVE_UP
FACE_UP
MOVE_DOWN
FACE_DOWN
MOVE_LEFT
FACE_LEFT
MOVE_RIGHT
FACE_RIGHT
Member Function Documentation
static std::shared_ptr<SpriteData> Game::SpriteMovementMotor::defaultSpriteData () inline static
Create a default SpriteData POD.
Returns
Default SpriteData
static bool Game::SpriteMovementMotor::updateSprite (const std::shared_ptr< SpriteData > data, const SpriteState current_state, const double delta) inline static
General sprite update for each reactor.
Parameters
[in] data Sprite data
[in] current_state The current sprite state
[in] delta The update delta
Returns
true if sprite is still moving, false otherwise
References MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT, and MOVE_UP.
Referenced by Game::SpriteMovementMotor::MoveUpReactor::updateState(), Game::SpriteMovementMotor::MoveDownReactor::updateState(), Game::SpriteMovementMotor::MoveLeftReactor::updateState(), and Game::SpriteMovementMotor::MoveRightReactor::updateState().
The documentation for this struct was generated from the following file:
src/game/sprite_movement.h