Nymph Game Engine: Events::Subject Class Reference
Events::Subject Class Reference
Class for a subject that an observer would observe for changes.
#include <subject.h>
Public Member Functions
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Detailed Description
Class for a subject that an observer would observe for changes.
Constructor & Destructor Documentation
virtual Events::Subject::~Subject () virtual default
Member Function Documentation
void Events::Subject::addObserver (std::shared_ptr< Observer > observer) virtual
Adds an observer.
Parameters
[in] observer The observer
Referenced by generated::getSubjectModule().
void Events::Subject::notify (std::shared_ptr< Event > event) virtual
notify is used to tell observers of an event.
Parameters
[in] event The event
Referenced by Game::SpriteMovementMotor::MoveUpReactor::enterState(), Game::SpriteMovementMotor::MoveDownReactor::enterState(), Game::SpriteMovementMotor::MoveLeftReactor::enterState(), Game::SpriteMovementMotor::MoveRightReactor::enterState(), generated::getSubjectModule(), Graphics::Camera::onStart(), Graphics::TileAnimator< StateType >::onStart(), Graphics::Camera::onUpdate(), Utility::DebugParser::parseCommand(), and Input::InputSystem::pollForInput().
void Events::Subject::notifyNow (std::shared_ptr< Event > event) virtual
notifyNow is used to tell observers of an event as an interrupt.
Parameters
[in] event The event
Referenced by Utility::FPSCounter::assessCountAndGetDelta(), Game::SpriteMovementMotor::MoveUpReactor::enterState(), Game::SpriteMovementMotor::FaceUpReactor::enterState(), Game::SpriteMovementMotor::MoveDownReactor::enterState(), Game::SpriteMovementMotor::FaceDownReactor::enterState(), Game::SpriteMovementMotor::MoveLeftReactor::enterState(), Game::SpriteMovementMotor::FaceLeftReactor::enterState(), Game::SpriteMovementMotor::MoveRightReactor::enterState(), Game::SpriteMovementMotor::FaceRightReactor::enterState(), generated::getSubjectModule(), Graphics::UI::TextField::onKeyDown(), Graphics::UI::QuitButton::onLeftClick(), Graphics::UI::TextField::onLeftClick(), and Graphics::TileAnimator< StateType >::onUpdate().
void Events::Subject::removeObserver (std::shared_ptr< Observer > observer) virtual
Removes an observer.
Parameters
[in] observer The observer
Referenced by generated::getSubjectModule().
The documentation for this class was generated from the following files:
src/events/subject.h
src/events/subject.cpp