Nymph Game Engine: Game::SpriteMovementMotor::MoveUpReactor Class Reference
Game::SpriteMovementMotor::MoveUpReactor Class Reference
#include <sprite_movement.h>
Public Member Functions
MoveUpReactor (const std::shared_ptr< SpriteData > &data, Events::Subject *subject)
virtual void enterState () override
enterState is called upon triggering of this state
virtual bool updateState (const double delta, SpriteInput &t) override
virtual SpriteState react (const SpriteInput transition) override
Public Member Functions inherited from Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >
StateReactor ()=delete
StateReactor (const SpriteState &state_type, const std::shared_ptr< SpriteData > &data_to_mutate, Subject *subject)
StateReactor constructor. This sets which state this reactor is for and sets the data to be mutated.
constexpr SpriteState getStateType () const noexcept
virtual bool updateState (const double delta, SpriteInput &transition_type)
updateState is called once per engine loop for timed updates
virtual void leaveState ()
leaveState is called upon triggering of a new state from this state.
virtual SpriteState react (const SpriteInputtransition)
This function is used to set up reactions for different types of transitions for this state.
Additional Inherited Members
Protected Attributes inherited from Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >
std::shared_ptr< SpriteData > data
Subject * subject
SpriteState state_type
Constructor & Destructor Documentation
Game::SpriteMovementMotor::MoveUpReactor::MoveUpReactor (const std::shared_ptr< SpriteData > & data, Events::Subject * subject) inline
Member Function Documentation
virtual void Game::SpriteMovementMotor::MoveUpReactor::enterState () inline override virtual
enterState is called upon triggering of this state
Reimplemented from Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >.
References Game::SpriteMoveEvent::create(), Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >::data, Game::SpriteMovementMotor::MOVE_UP, Events::Subject::notify(), Events::Subject::notifyNow(), and Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >::subject.
virtual SpriteState Game::SpriteMovementMotor::MoveUpReactor::react (const SpriteInput transition) inline override virtual
References Game::SpriteMovementMotor::FACE_UP, Game::SpriteMovementMotor::MOVE_UP, and Game::SpriteMovementMotor::NONE.
virtual bool Game::SpriteMovementMotor::MoveUpReactor::updateState (const double delta, SpriteInput & t) inline override virtual
References Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >::data, Events::FSM::StateReactor< SpriteData, SpriteState, SpriteInput >::getStateType(), Game::SpriteMovementMotor::NONE, and Game::SpriteMovementMotor::updateSprite().
The documentation for this class was generated from the following file:
src/game/sprite_movement.h